# Generated by Django 5.1.7 on 2025-04-09 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('proveedor', models.BooleanField(default=False)),
                ('cliente', models.BooleanField(default=False)),
                ('logistica', models.BooleanField(default=False)),
                ('ruc', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('paginaWeb', models.CharField(blank=True, max_length=255, null=True)),
                ('formaPago', models.CharField(blank=True, max_length=255, null=True)),
                ('favorito', models.BooleanField(default=False)),
                ('adjunto', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('traza', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('departamento', models.TextField(blank=True, null=True)),
                ('requisitos_ingreso', models.TextField(blank=True, null=True)),
                ('horario_atencion', models.TextField(blank=True, null=True)),
                ('ediciones', models.TextField(blank=True, null=True)),
                ('traza', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('celular', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('ediciones', models.TextField(blank=True, null=True)),
                ('traza', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DatoGeneralProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_req', models.CharField(max_length=255, verbose_name='Código de Requerimiento')),
                ('nombre_producto', models.TextField(verbose_name='Nombre del Producto')),
                ('prioridad', models.CharField(default='Baja', max_length=100, verbose_name='Prioridad')),
                ('otros_costos_factura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Otros Costos con Factura')),
                ('costos_sin_factura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costos sin Factura')),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de Registro')),
                ('estado', models.CharField(default='1', max_length=100, verbose_name='Estado')),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to='adjuntos/', verbose_name='Adjuntos')),
                ('transporte_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Transporte Estimado (S/.)')),
                ('gm_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='GM % Deseado')),
                ('producto_entregado', models.BooleanField(default=False, verbose_name='Producto Entregado')),
                ('ediciones', models.TextField(blank=True, null=True, verbose_name='Historial de Ediciones')),
                ('traza', models.IntegerField(blank=True, null=True, verbose_name='TRAZA')),
                ('contacto_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.contacto', verbose_name='Contacto Cliente')),
                ('lugar_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lugar', verbose_name='Lugar de Entrega al Cliente')),
            ],
        ),
    ]
