# Generated by Django 4.2 on 2025-12-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgeneralesordencompraaproveedores',
            name='proveedorContacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='api.contactos'),
        ),
    ]
