# Generated by Django 5.1.7 on 2025-04-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='contactos',
        ),
        migrations.RenameModel(
            old_name='DatoGeneralProceso',
            new_name='datos_generales_del_proceso',
        ),
        migrations.RenameModel(
            old_name='Empresa',
            new_name='empresas',
        ),
        migrations.RenameModel(
            old_name='Lugar',
            new_name='lugares',
        ),
    ]
