# Generated by Django 4.2 on 2025-10-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPrueba',
            fields=[
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('codigoBarra', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('anaquel', models.IntegerField(blank=True, null=True)),
                ('fechaIngreso', models.DateTimeField(blank=True, null=True)),
                ('fechaModificacion', models.DateTimeField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('ediciones', models.TextField(blank=True, null=True)),
                ('TRAZA', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
