# Generated by Django 4.2 on 2025-11-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detracciones',
            old_name='comprobante_de_pago',
            new_name='comprobanteDePago',
        ),
    ]
