# Generated by Django 5.1.7 on 2025-04-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_contacto_contactos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='cod_req',
            new_name='codReq',
        ),
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='contacto_cliente',
            new_name='contactoCliente',
        ),
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='costos_sin_factura',
            new_name='costosSinFactura',
        ),
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='fecha_registro',
            new_name='fechaRegistro',
        ),
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='gm_porcentaje',
            new_name='gmPorcentaje',
        ),
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='lugar_entrega',
            new_name='lugarEntrega',
        ),
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='nombre_producto',
            new_name='nombreProducto',
        ),
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='otros_costos_factura',
            new_name='otrosCostosFactura',
        ),
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='producto_entregado',
            new_name='productoEntregado',
        ),
        migrations.RenameField(
            model_name='datos_generales_del_proceso',
            old_name='transporte_estimado',
            new_name='transporteEstimado',
        ),
        migrations.RenameField(
            model_name='lugares',
            old_name='horario_atencion',
            new_name='horarioAtencion',
        ),
        migrations.RenameField(
            model_name='lugares',
            old_name='requisitos_ingreso',
            new_name='requisitosIngreso',
        ),
    ]
