# Generated by Django 4.2 on 2025-12-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datosgeneralesordencompraaproveedores_proveedorcontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosgeneralesordencompraaproveedores',
            name='proveedor',
        ),
    ]
