# Generated by Django 4.2 on 2025-12-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_datosgeneralesordencompraaproveedores_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosgeneralesordencompraaproveedores',
            old_name='proveedorContacto',
            new_name='proveedor',
        ),
    ]
