# Generated by Django 4.2 on 2026-01-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_proveedorcontacto_datosgeneralesordencompraaproveedores_proveedor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datosgeneralesdelproceso',
            index=models.Index(fields=['submissionDate', 'estado'], name='idx_datosgen_fecha_estado'),
        ),
    ]
